### ISSUE TITLE
Change log?

### ISSUE THREAD

**Issue by AnderssonPeter** [seznam/gulp-brotli#4]
Hi do you have a change log for this project?

**Comment by jurca** [comment]
Hello, no, sorry, I do not have a changelog. What information do you seek?

**Comment by AnderssonPeter** [comment]
What changed between 2.0.2 and 3.0.0, its a major version change?

**Comment by jurca** [comment]
The 2.x versions were relying on a binary library providing the brotli support, which sometimes resulted in compatibility issues when compiling the library during `npm install` against the node version you were using.

The 3.x version switched to implementation provided by Node's [zlib](https://nodejs.org/docs/latest-v10.x/api/zlib.html) module (introduced in Node.js 10).

This is a major change because it means dropping support for Node 9 or older.
